config/routes.rb
Rails.application.routes.draw do

  root 'herds#index'
  resources :cats

  resources :herds do
    resources :cats
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :herd
end

app/models/herd.rb
class Herd < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
before_action :find_herd
  def index
    p "#"*30
    p params
    p "#"*30
    @cats = @herd.cats
  end
  def new
    @herd = Herd.find(params[:herd_id])
    @cat = Cat.new

  end
  def create
    @cat = Cat.new()
  end

  private
  def find_herd
    if params[:herd_id]
      @herd = Herd.find(params[:herd_id])
    end
  end

  def cat_params
    params.require(:cat).permit(:name, :age)
  end
end

app/controllers/herds_controller.rb
class HerdsController < ApplicationController
  before_action :set_herd, only: [:show, :edit, :update, :destroy]

  # GET /herds
  # GET /herds.json
  def index
    @herds = Herd.all
  end

  # GET /herds/1
  # GET /herds/1.json
  def show
    @herd = Herd.find(params[:id])
    respond_to do |f|
      f.js
      f.html {render json: @herd.cats}
    end
  end

  # GET /herds/new
  def new
    @herd = Herd.new
  end

  # GET /herds/1/edit
  def edit
  end

  # POST /herds
  # POST /herds.json
  def create
    @herd = Herd.new(herd_params)

    respond_to do |format|
      if @herd.save
        format.html { redirect_to @herd, notice: 'Herd was successfully created.' }
        format.json { render :show, status: :created, location: @herd }
      else
        format.html { render :new }
        format.json { render json: @herd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /herds/1
  # PATCH/PUT /herds/1.json
  def update
    respond_to do |format|
      if @herd.update(herd_params)
        format.html { redirect_to @herd, notice: 'Herd was successfully updated.' }
        format.json { render :show, status: :ok, location: @herd }
      else
        format.html { render :edit }
        format.json { render json: @herd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /herds/1
  # DELETE /herds/1.json
  def destroy
    @herd.destroy
    respond_to do |format|
      format.html { redirect_to herds_url, notice: 'Herd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herd
      @herd = Herd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def herd_params
      params.require(:herd).permit(:cats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/herds_helper.rb
module HerdsHelper
end

app/views/cats/_form.html.erb
<%= form_for(cat) do |f| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/index.html.erb
<%=@cats %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/herds/_form.html.erb
<%= form_for(herd) do |f| %>
  <% if herd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(herd.errors.count, "error") %> prohibited this herd from being saved:</h2>

      <ul>
      <% herd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cats %>
    <%= f.text_field :cats %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/herds/_herd.html.erb
<%=herd.name%>
<%=link_to 'Add new cat', new_herd_cat_path(herd) %>

app/views/herds/edit.html.erb
<h1>Editing Herd</h1>

<%= render 'form', herd: @herd %>

<%= link_to 'Show', @herd %> |
<%= link_to 'Back', herds_path %>

app/views/herds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Herds</h1>

<table>
  <thead>
    <tr>
      <th>Cats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @herds.each do |herd| %>
      <tr>
        <td><%= herd.name %></td>
        <td><%= link_to 'Show', herd, remote: true %></td>
        <td><%= link_to 'Edit', edit_herd_path(herd) %></td>
        <td><%= link_to 'Destroy', herd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="container"></div>
<br>

<%= link_to 'New Herd', new_herd_path %>

app/views/herds/new.html.erb
<h1>New Herd</h1>

<%= render 'form', herd: @herd %>

<%= link_to 'Back', herds_path %>

app/views/herds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cats:</strong>
  <%= @herd.cats %>
</p>

<%= link_to 'Edit', edit_herd_path(@herd) %> |
<%= link_to 'Back', herds_path %>
<%= link_to 'Add cat' new_herd_cat %>

app/views/herds/show.js.erb
$('#container').append("<%=j (render @herd) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>